# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: detector.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'detector.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x65tector.proto\x12\x08\x64\x65tector\"]\n\rDetectRequest\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\r\n\x05\x63\x61lib\x18\x04 \x03(\x02\x12\x10\n\x08treshold\x18\x05 \x01(\x02\"$\n\x0e\x44\x65tectResponse\x12\x12\n\ndetections\x18\x01 \x03(\t2G\n\x08\x44\x65tector\x12;\n\x06\x44\x65tect\x12\x17.detector.DetectRequest\x1a\x18.detector.DetectResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'detector_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DETECTREQUEST']._serialized_start=28
  _globals['_DETECTREQUEST']._serialized_end=121
  _globals['_DETECTRESPONSE']._serialized_start=123
  _globals['_DETECTRESPONSE']._serialized_end=159
  _globals['_DETECTOR']._serialized_start=161
  _globals['_DETECTOR']._serialized_end=232
# @@protoc_insertion_point(module_scope)
