dataset:
  type: 'kitti'
  data_dir: 'zdata/KITTI/object/'
  root_dir: '/home/akos/Documents/code/MonoDetectors'
  label_dir: 'zdata/KITTI/object/training/label_2'
  eval_cls: ['Car']
#  eval_cls: ['Car','Pedestrian','Cyclist']
  batch_size: 1
  num_workers: 12
  class_merging: False
  use_dontcare: False
  use_3d_center: True
  writelist: ['Car','Pedestrian','Cyclist']
  random_flip: 0.5
  random_crop: 0.5
  scale: 0.4
  shift: 0.1
  drop_last_val: True

trainer:
  log_dir: 'MonoLSS/logs/'
  out_dir: 'MonoLSS/output/'
  # resume_model: 'model.pth'

tester:
  threshold: 0.2  # confidence filter
  out_dir: './MonoLSS/testset_out'
  resume_model: './checkpoints/model.pth' # pre-trained model path

model:
  type: 'MonoLSS'
  backbone: 'dla34'
  neck: 'DLAUp'
