type: 'MonoLSS'
MonoLSS:
  type: 'MonoLSS'
  threshold: 0.2
  resume_model: './checkpoints/monolss.pth' # pre-trained model path
  backbone: 'dla34'
  neck: 'DLAUp'
  cls: ['Car','Pedestrian','Cyclist']
  resolution: [1280, 384]
  max_objs: 50
  downsample: 4
  cls_mean_size: [[1.76255119    ,0.66068622   , 0.84422524   ],
                  [1.52563191462 ,1.62856739989, 3.88311640418],
                  [1.73698127    ,0.59706367   , 1.76282397   ]]

